version: '3.7'

services:
 currency-exchange:
     image: ackerman4levi/currency-exchange-service01:0.0.1-SNAPSHOT
     mem_limit: 700m
     ports:
       - "8016:8016"
     networks:
       - currency-network
     depends_on:
      - naming-server
      - rabbitmq
     environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit

 currency-conversion:
     image: ackerman4levi/currency-conversion-service:0.0.1-SNAPSHOT
     mem_limit: 700m
     ports:
       - "8101:8101"
     networks:
       - currency-network
     depends_on:
      - naming-server
      - rabbitmq
     environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit

 api-gateaway:
     image: ackerman4levi/api-gateaway:0.0.1-SNAPSHOT
     mem_limit: 700m
     ports:
       - "8765:8765"
     networks:
       - currency-network
     depends_on:
      - naming-server
      - rabbitmq 
     environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit

 naming-server:
     image: ackerman4levi/naming-server:0.0.1-SNAPSHOT
     mem_limit: 700m
     ports:
       - "8761:8761"
     networks:
       - currency-network

 zipkin-server:
     image: openzipkin/zipkin:2.23
     mem_limit: 300m
     ports:
       - "9411:9411"
     networks:
       - currency-network
     environment:
       RABBIT_URI: amqp://guest:guest@rabbitmq:5672
     depends_on:
       - rabbitmq  
     restart: always #Restart if there is a problem starting up


 rabbitmq:
     image: rabbitmq:3.8.12-management
     mem_limit: 300m
     ports:
       - "5672:5672"
       - "15672:15672"
     networks:
       - currency-network


networks:
  currency-network: